export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Explore } from "./Explore";
export { default as GetStarted } from "./GetStarted";
export { default as WhatsNew } from "./WhatsNew";
export { default as World } from "./World";
export { default as Insights } from "./Insights";
export { default as Feedback } from "./Feedback";
export { default as Footer } from "./Footer";
